HW3 completed with *-task
vagafonov/otus-go pull request #3
Opened 2023-01-04 09:00 UTC by vagafonov

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-01-04 21:31 UTC, vladislavmass requested changes
Работа в целом хорошая, радует что использовали регулярные выражения. На текущий момент работа не поддерживает работу с go get и это не правильно. Также к работе есть ряд стилистических замечаний.

Новые unit тесты отсутствуют.

2023-01-04 21:31 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +		wordsStructured = append(wordsStructured, struct {
Идет добавление в слайс элементов типа анонимная структура и в данном случае непонятно зачем это делать. Предлагаю добавлять в массив элементы типа word.

2023-01-04 21:31 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +	type word struct {
Название структуры не отражает ее суть. Предлагаю подобрать более говорящие имя.

2023-01-04 21:31 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +	result := make([]string, 0)
Имя переменных в этом блоке не отображает назначениях этих переменных

2023-01-04 21:31 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +	for k := range wordsStructured {
В данном случае ради возврата создается новый массив, делается несколько аллокаций памяти  и несколько копирований данных. Предлагаю либо избавится от этой операции либо при создание задать слайсу нужный капасити.

2023-01-05 10:46 UTC, vagafonov commented on hw03_frequency_analysis/top.go
> +		wordsStructured = append(wordsStructured, struct {
Исправил

2023-01-05 10:46 UTC, vagafonov commented on hw03_frequency_analysis/top.go
> +	type word struct {
Переимновал

2023-01-05 10:47 UTC, vagafonov commented on hw03_frequency_analysis/top.go
> +	result := make([]string, 0)
Переимновал

2023-01-05 10:49 UTC, vagafonov commented on hw03_frequency_analysis/top.go
> +	for k := range wordsStructured {
Не знаю как без лишней итерации и лишних перменных имзенить струтктуру существующего слайса. 
Добавил capacity.

2023-01-05 11:11 UTC, vladislavmass approved these changes
Работа принята.10/10

2023-01-05 11:11 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +	for k := range wordsForSortSlice {
Я бы перед этой строкой все таки рекомендовал сделать так. 
`
resultCount:=10
if len(wordsForSortSlice)<resultCount{ 
resultCount=len(wordsForSortSlice) 
} 
result := make([]string, 0, resultCount)
`

2023-01-05 12:07 UTC, merged