Hw04 lru cache
vagafonov/otus-go pull request #4
Opened 2023-01-05 20:20 UTC by vagafonov

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-01-05 20:55 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	tail   ListItem
head и tail лучше сделать указателями.

2023-01-05 20:55 UTC, hungry-honeybadger commented on hw04_lru_cache/list.go
> +	if l.head == (ListItem{}) { // Проверка на пустое значение свойства head. Это ОК ?
Если изменить head на указатель, то тут просто нужна проверка на nil. Также не учтена ситуация когда лист пустой и PushFront одновременно добавит и первый и последний элемент.

2023-01-05 20:55 UTC, hungry-honeybadger commented on hw04_lru_cache/list.go
> +	if l.tail == (ListItem{}) { // Проверка на пустое значение свойства head. Это ОК ?
Тут тоже самое замечание что и для PushFront.

2023-01-06 12:39 UTC, vagafonov commented on hw04_lru_cache/list.go
> +	tail   ListItem
Да спасибо, в этом была проблема

2023-01-06 12:41 UTC, vagafonov commented on hw04_lru_cache/list.go
> +	if l.head == (ListItem{}) { // Проверка на пустое значение свойства head. Это ОК ?
Изменил head на указатель. Про пустой фронт не совсем понял...

2023-01-06 12:41 UTC, vagafonov commented on hw04_lru_cache/list.go
> +	if l.tail == (ListItem{}) { // Проверка на пустое значение свойства head. Это ОК ?
Изменил tail на указатель

2023-01-06 21:05 UTC, vladislavmass requested changes
В задание нарушен изначальный контракт.

2023-01-06 21:05 UTC, hungry-honeybadger commented on hw04_lru_cache/list.go
> +	Dump() []interface{}
Можно указать метод для структуры которого нет в интерфейсе. Но если тип l объявлен как интерфейс( как например в структуре lruCahcr), то методы dump будет иметь только методы интерфейса. И прошу учитывать такой момент что контракт( он же интерфейс) менять нельзя

2023-01-06 21:05 UTC, hungry-honeybadger commented on hw04_lru_cache/list.go
> +		// TODO ? Мало удалить сам элемент (i = nil) кроме этого нужно удалить все сылки на него l.head, i.Next.Prev ?
Да, надо удались все ссылки на этот элемент.

2023-01-06 21:05 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	*/
Да, равнозначны. Вариант зависит от использования. Если в коде надо постояно оперировать с указателям( как тут) то лучше сразу указатель, если же надо часто менять значения внутри объекта, то проще использовать объект и брать указатель только там где он нужен.

2023-01-07 09:16 UTC, vladislavmass approved these changes
Работа принята. 10/10

2023-01-07 09:16 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	if cache.items[key] != nil {
В данном случае ок. Но я бы рекомендовал использовать для проверки наличия элемента в мапе синтаксис вида ` if _,ok:= cache.items[key];!ok`

2023-01-07 09:16 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +func (cache lruCache) Clear() {
Принимается. Но можно было просто пересоздать мапу и list.

2023-01-07 09:50 UTC, merged