Hw05 parallel execution
vagafonov/otus-go pull request #5
Opened 2023-01-15 19:05 UTC by vagafonov

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-01-15 22:37 UTC, dshemin requested changes

2023-01-15 22:37 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	ch := make(chan Task, 100)
Критично:

Тут две проблемы:

1. Критичная - если прийдёт 101 таска на выполнение - мы получим deadlock так, как буфере канала есть место только для 100 задач и ни кто канал не обрабатывает.

2. Не критичная, но важная. У нас уже выделена память под T задач и мы ещё дополнительно выделим памяти под T задач. В итоге потребление памяти вырастет в два раза. Тут можно сделать без буферезированного канала.

2023-01-15 22:37 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	for i := 0; i < n; i++ {
Важно:

Если n <= 0 мы просто ничего не сделаем с задачами. Стоит обработать такую ситуация и явно сказать пользователю, что данные неверные.

2023-01-15 22:37 UTC, dshemin commented on hw05_parallel_execution/run.go
> +							return
Критично:

По задаче, нам надо прекратить обработку задач, т.е. завершить ВСЕ горутины, если количество ошибок превысило порог. Тут мы завершаем только ту, в которой возникла ошибка. Контрпример:

У нас 10 задач
N = 2
M = 1

Первая задача завершается с ошибкой, остальные нет.

Мы закрываем горутину в которой обрабатывалась первая задача, но вторая горутина продолжит работу.

2023-01-15 22:37 UTC, dshemin commented on hw05_parallel_execution/run.go
> +					if m > 0 {
Важно:

Можно объединить это условие и условие на строке ниже в одно.

2023-01-15 22:37 UTC, dshemin commented on hw05_parallel_execution/run.go
> +					errorsCountSafe := errorsCount
Критично:

Мы всё равно используем значение вне критической секции. Да, формально гонки нет мы не читаем из одной области памяти, но будет такая ситуация, при которой мы закроем горутину когда количество ошибок уже превысило порог, т.е. мы уже выполним больше задач чем нужно.

2023-01-17 18:58 UTC, vagafonov commented on hw05_parallel_execution/run.go
> +	ch := make(chan Task, 100)
Первое замечанре исправил. Второе замечание пытался реализовать при помощи небуфферизированного канала но у меня не получилось.

2023-01-17 18:58 UTC, vagafonov commented on hw05_parallel_execution/run.go
> +	for i := 0; i < n; i++ {
Добавил проверку и тест

2023-01-17 19:05 UTC, vagafonov commented on hw05_parallel_execution/run.go
> +							return
Перенес условие проверки выхода в начало цикла, получающего задачу из канала.

Я наверное не совсем понял что значит «завершить горутину». 
Есть 2 варианта заврешения до выполнения задачи:
1 проверить условие до выполненяи задачи (как сейчас)
2 проверить условие в самой задачи.

Для задачи асинхронной обработки, всегда на первой итерации получения задач из канала, все колличество горутин возьмет в обработку по одной задаче и только при следующей итерации задач будет проверено колличество накопленных ошибок.

2023-01-17 19:07 UTC, vagafonov commented on hw05_parallel_execution/run.go
> +					if m > 0 {
Разнес проверки в разны части и типерь это неактуально

2023-01-17 19:08 UTC, vagafonov commented on hw05_parallel_execution/run.go
> +					errorsCountSafe := errorsCount
Кажется поправил, путем выноса проверки в начало цикла

2023-01-18 08:11 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	ch := make(chan Task, 100)
А что именно не получилось?

2023-01-18 08:13 UTC, dshemin commented on hw05_parallel_execution/run.go
> +							return
Завершить горутину, в данном конкретном случае, это закрыть канал с которого она принимает задачи.

2023-01-18 10:30 UTC, dshemin requested changes

2023-01-18 10:30 UTC, dshemin commented on hw05_parallel_execution/run.go
> +					mu.Lock()
Кртично:

Вам надо весь блок обернуть в lock/unlock

2023-01-19 19:03 UTC, vagafonov commented on hw05_parallel_execution/run.go
> +							return
Исправил

2023-01-19 19:03 UTC, vagafonov commented on hw05_parallel_execution/run.go
> +					mu.Lock()
В таком случае все зависает

2023-01-19 19:04 UTC, vagafonov commented on hw05_parallel_execution/run.go
> +	ch := make(chan Task, 100)
Все зависает

2023-01-24 18:02 UTC, dshemin requested changes

2023-01-24 18:02 UTC, dshemin commented on hw05_parallel_execution/run.go
> +			mu.Lock()
Обратите внимание что вы берёте лок в начале цикла, т.е. Неважно сколько воркеров, у нас будет работать только один. В лок надо взять ТОЛЬКО секцию инкремента и подсчёта ошибок.

2023-01-27 06:50 UTC, dshemin approved these changes

2023-01-27 06:50 UTC, dshemin commented on hw05_parallel_execution/run.go
> +						_, ok := <-ch
Важно:

Так делать не надо. Канал должен закрывать тот, кто его открыл. Иначе, рано или поздно, столкнётесь с паниками, когда ваш попытается закрыть уже закрытый канал.

2023-01-27 06:50 UTC, dshemin commented on hw05_parallel_execution/run.go
> +					if atomic.LoadInt32(&errorsCount) >= int32(m) {
Важно:

Лучше данный код выполнять в цикле, который отправляет задачи.

2023-02-08 06:33 UTC, merged